# Book settings
title: The pyOpenSci Developer Guide
author: The pyOpenSci Community
logo: images/logo/logo.png  

repository:
  url: https://github.com/pyOpenSci/dev_guide

html:
  favicon: images/logo/logo.png
  google_analytics_id: UA-165151943-1 
  use_edit_page_button: true
  home_page_in_navbar: false